"""tables

Revision ID: 63d0ef022beb
Revises: df92842e6af8
Create Date: 2023-04-11 16:21:57.397891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d0ef022beb'
down_revision = 'df92842e6af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.drop_column('types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('types', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
